-- 코드를 입력하세요
SELECT P.PRODUCT_ID,	P.PRODUCT_NAME,	sum(P.PRICE*O.AMOUNT) as TOTAL_SALES
from FOOD_PRODUCT P
join FOOD_ORDER O on P.PRODUCT_ID = O.PRODUCT_ID
where year(O.PRODUCE_DATE)=2022 and month(O.PRODUCE_DATE)=5
group by PRODUCT_NAME
order by TOTAL_SALES desc, P.PRODUCT_ID asc