-- 코드를 입력하세요
SELECT P.MEMBER_NAME,	R.REVIEW_TEXT,	R.REVIEW_DATE
from MEMBER_PROFILE P
join REST_REVIEW R on P.MEMBER_ID = R.MEMBER_ID
WHERE 
    P.MEMBER_ID = (
        SELECT MEMBER_ID 
        FROM REST_REVIEW 
        GROUP BY MEMBER_ID 
        ORDER BY COUNT(*) DESC 
        LIMIT 1
    )
order by R.REVIEW_DATE asc, R.REVIEW_TEXT asc